name: Build and deploy Node.js app to Azure Web App - backend-hirez

on:
  push:
    branches:
      - draft
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: ./Backend    # Change directory to the backend folder
        run: npm install

      - name: Build backend
        working-directory: ./Backend    # Change directory to the backend folder
        run: npm run build --if-present

      - name: Test backend
        working-directory: ./Backend    # Change directory to the backend folder
        run: npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./Backend/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./Backend   # Unzip the backend artifact into the backend folder

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'backend-hirez'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
          package: ./Backend
